// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7JL_kZgyqsLUTQE2kZFkJAhNSqrGHJw8',
    appId: '1:766535907119:web:0022f4f5a9d208eebd53da',
    messagingSenderId: '766535907119',
    projectId: 'my-job-task-trips',
    authDomain: 'my-job-task-trips.firebaseapp.com',
    storageBucket: 'my-job-task-trips.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqi4Wt8wImtEBZJ3wzFi5qqYONDTgFhkM',
    appId: '1:766535907119:android:b30e36f903b2b0ccbd53da',
    messagingSenderId: '766535907119',
    projectId: 'my-job-task-trips',
    storageBucket: 'my-job-task-trips.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEgdnutYOzk77t4CB2XOX6xyHBqiiBVjY',
    appId: '1:766535907119:ios:d52075aa4e6a87d5bd53da',
    messagingSenderId: '766535907119',
    projectId: 'my-job-task-trips',
    storageBucket: 'my-job-task-trips.firebasestorage.app',
    iosBundleId: 'com.example.users',
  );
}
